/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package poligon;

import java.lang.Math;
import java.util.Random;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        double x = (Math.random() - 0.5) * 5;
        double y = Math.tanh(x);
        System.out.println(new App().getGreeting());
        System.out.println("x = " + x);
        System.out.println("y = " + y);
    }
}
